# 生产环境
spring:
  datasource:
    #=======================================使用阿里巴巴的Druid数据源===================================================
    type: com.alibaba.druid.pool.DruidDataSource
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
    #==============================================================================================================

    #=============================================常用数据库的基本配置=================================================
    # MySQL配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/quick-start?characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username:
    password:
  redis:
    host: xxx
    port: 6379
    password: xxx
mybatis:
  mapper-locations: mappers/**/**/*.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 配置swagger
swagger:
  title: quick-start API Document
  description: 接口文档
  version: 1.0
logging:
  config: classpath:logback.xml